import img from "./Assets/logoImage/1.png";
import img2 from "./Assets/logoImage/2.png";
import img3 from "./Assets/logoImage/3.png";
import img4 from "./Assets/logoImage/4.png";
import img5 from "./Assets/logoImage/5.png";
import img6 from "./Assets/logoImage/6.png";
import img7 from "./Assets/logoImage/7.png";
import img8 from "./Assets/logoImage/8.png";
import img9 from "./Assets/logoImage/9.png";
import img10 from "./Assets/logoImage/10.png";
import img12 from "./Assets/logoImage/12.png";
import img13 from "./Assets/logo/13.png";
import leylaq from "./Assets/logoImage/leylaq.png";
import muc from "./Assets/logoImage/muc&mer.png";
import solo from "./Assets/logoImage/solo.png";
import sefa from "./Assets/logoImage//sefa.png";
import mufa from "./Assets/logoImage/mufa.png";
import reyhan from "./Assets/logoImage/reyhan.png";
import burger from "./Assets/logoImage/1312.png";
import lobik from "./Assets/logoImage/lobik.png";
import fried from "./Assets/logoImage/FredMondy.png";
import pion from "./Assets/logoImage/pion.png";
import hesiar from "./Assets/logoImage/hisaralti.png";
import soon from "./Assets/logoImage/soon.png";

export const data = [
  {
    id: 1,
    name: "Tereyağlı Yumurta / Omlet",
    price: "70 ₺",
    img: leylaq,
    cat: "Sıcak Kahvaltılıklar",
    brand: 1,
  },
  {
    id: 2,
    name: "Menemen",
    price: "80 ₺",
    img: leylaq,
    cat: "Sıcak Kahvaltılıklar",
    brand: 1,
  },
  {
    id: 3,
    name: "Sucuklu Yumurta",
    price: "95 ₺",
    img: leylaq,
    cat: "Sıcak Kahvaltılıklar",
    brand: 1,
  },
  {
    id: 4,
    name: "Kavurmalı Yumurta",
    price: "105 ₺",
    img: leylaq,
    cat: "Sıcak Kahvaltılıklar",
    brand: 1,
  },
  {
    id: 5,
    name: "Kaşarlı",
    price: "130 ₺",
    img: leylaq,
    cat: "Gözleme Çeşitleri",
    brand: 1,
  },
  {
    id: 6,
    name: "Lor Peynirli",
    price: "130 ₺",
    img: leylaq,
    cat: "Gözleme Çeşitleri",
    brand: 1,
  },
  {
    id: 7,
    name: "Antep Peynirli",
    price: "130 ₺",
    img: leylaq,
    cat: "Gözleme Çeşitleri",
    brand: 1,
  },
  {
    id: 8,
    name: "Patatesli",
    price: "130 ₺",
    img: leylaq,
    cat: "Gözleme Çeşitleri",
    brand: 1,
  },
  {
    id: 9,
    name: "Kalem Böreği",
    price: "75 ₺",
    info: "6 Adet",
    img: leylaq,
    cat: "Börek - Kızartmalıklar",
    brand: 1,
  },
  {
    id: 10,
    name: "Çi Börek - Peynirli",
    price: "20 ₺",
    info: "Adet",
    img: leylaq,
    cat: "Börek - Kızartmalıklar",
    brand: 1,
  },
  {
    id: 11,
    name: "Paçanga Böreği",
    price: "20 ₺",
    info: "Adet",
    img: leylaq,
    cat: "Börek - Kızartmalıklar",
    brand: 1,
  },
  {
    id: 12,
    name: "Pişi",
    price: "15 ₺",
    info: "Adet",
    img: leylaq,
    cat: "Börek - Kızartmalıklar",
    brand: 1,
  },
  {
    id: 13,
    name: "Patates Kızartması",
    price: "45 ₺",
    info: "PRS",
    img: leylaq,
    cat: "Börek - Kızartmalıklar",
    brand: 1,
  },
  {
    id: 14,
    name: "Kızartma Tabağı ",
    price: "110 ₺",
    info: "Kalem böreği, çi börek, paçanga böreği, patates",
    img: leylaq,
    cat: "Börek - Kızartmalıklar",
    brand: 1,
  },
  {
    id: 15,
    name: "Humus",
    price: "80 ₺",
    img: muc,
    cat: "Soğuk Mezeler",
    brand: 2,
  },
  {
    id: 16,
    name: "Babagannuş",
    price: "80 ₺",
    img: muc,
    cat: "Soğuk Mezeler",
    brand: 2,
  },
  {
    id: 17,
    name: "Rus Salatası",
    price: "80 ₺",
    img: muc,
    cat: "Soğuk Mezeler",
    brand: 2,
  },
  {
    id: 18,
    name: "Zeytin Salatası",
    price: "80 ₺",
    img: muc,
    cat: "Soğuk Mezeler",
    brand: 2,
  },
  {
    id: 19,
    name: "Acılı Ezme",
    price: "80 ₺",
    img: muc,
    cat: "Soğuk Mezeler",
    brand: 2,
  },
  {
    id: 20,
    name: "Atom",
    price: "80 ₺",
    img: muc,
    cat: "Soğuk Mezeler",
    brand: 2,
  },
  {
    id: 21,
    name: "Muhammara",
    price: "80 ₺",
    img: muc,
    cat: "Soğuk Mezeler",
    brand: 2,
  },
  {
    id: 22,
    name: "Bahar Cacığı",
    price: "80 ₺",
    img: muc,
    cat: "Soğuk Mezeler",
    brand: 2,
  },
  {
    id: 23,
    name: "Kuru Domates",
    price: "80 ₺",
    img: muc,
    cat: "Soğuk Mezeler",
    brand: 2,
  },
  {
    id: 24,
    name: "Tahinli Patlıcan",
    price: "80 ₺",
    img: muc,
    cat: "Soğuk Mezeler",
    brand: 2,
  },
  {
    id: 25,
    name: "Çerkez Tavuğu",
    price: "80 ₺",
    img: muc,
    cat: "Soğuk Mezeler",
    brand: 2,
  },
  {
    id: 26,
    name: "Falafel",
    price: "80 ₺",
    img: muc,
    cat: "Sıcak Mezeler",
    brand: 2,
  },
  {
    id: 27,
    name: "Mücver",
    price: "80 ₺",
    img: muc,
    cat: "Sıcak Mezeler",
    brand: 2,
  },
  {
    id: 28,
    name: "Fırın Mücver",
    price: "80 ₺",
    img: muc,
    cat: "Sıcak Mezeler",
    brand: 2,
  },
  {
    id: 29,
    name: "Şakşuka",
    price: "80 ₺",
    img: muc,
    cat: "Sıcak Mezeler",
    brand: 2,
  },
  {
    id: 30,
    name: "Söğürtme",
    price: "90 ₺",
    img: muc,
    cat: "Sıcak Mezeler",
    brand: 2,
  },
  {
    id: 31,
    name: "Kaşarlı Mantar",
    price: "90 ₺",
    img: muc,
    cat: "Sıcak Mezeler",
    brand: 2,
  },
  {
    id: 32,
    name: "Közlenmiş Kapya Biber",
    price: "60 ₺",
    img: muc,
    cat: "Sıcak Mezeler",
    brand: 2,
  },
  {
    id: 33,
    name: "Arnavut Ciğeri",
    price: "100 ₺",
    img: muc,
    cat: "Sıcak Mezeler",
    brand: 2,
  },
  {
    id: 34,
    name: "Seçeceğiniz 6 adet soğuk meze",
    price: "100 ₺",
    img: muc,
    cat: "Ordövr Tabağı",
    brand: 2,
  },
  {
    id: 35,
    name: "Margherita",
    price: "180 ₺",
    info: "Domates Sos, Mozzarella, Fesleğen, Zeytinyağı",
    img: solo,
    cat: "Pizza (Klasik Hamur - 30 CM)",
    brand: 3,
  },
  {
    id: 36,
    name: "Karışık",
    price: "210 ₺",
    info: "Sucuk, mantar, mısır, domates, zeytin",
    img: solo,
    cat: "Pizza (Klasik Hamur - 30 CM)",
    brand: 3,
  },
  {
    id: 37,
    name: "Tavuklu",
    price: "210 ₺",
    info: "Tavuk, sezar sos, marul",
    img: solo,
    cat: "Pizza (Klasik Hamur - 30 CM)",
    brand: 3,
  },
  {
    id: 38,
    name: "Green",
    price: "190 ₺",
    info: "Avokado, kuru domates, ıspanak, kapya biber",
    img: solo,
    cat: "Pizza (Klasik Hamur - 30 CM)",
    brand: 3,
  },
  {
    id: 39,
    name: "Special",
    price: "280 ₺",
    info: "Füme Kaburga, roka, parmesan peyniri",
    img: solo,
    cat: "Pizza (Klasik Hamur - 30 CM)",
    brand: 3,
  },
  {
    id: 40,
    name: "Ispanak Ricotta",
    price: "190 ₺",
    info: "Ispanak, tulum peyniri, zeytinyağı",
    img: solo,
    cat: "Pizza (Klasik Hamur - 30 CM)",
    brand: 3,
  },
  {
    id: 41,
    name: "Ton Balıklı",
    price: "210 ₺",
    info: "Ton Balığı, mısır, zeytin",
    img: solo,
    cat: "Pizza (Klasik Hamur - 30 CM)",
    brand: 3,
  },
  {
    id: 42,
    name: "Pepperoni",
    price: "250 ₺",
    info: "Özel sucuk, mantar",
    img: solo,
    cat: "Pizza (Klasik Hamur - 30 CM)",
    brand: 3,
  },
  {
    id: 43,
    name: "4 Peynirli",
    price: "240 ₺",
    info: "Mozeralla, gorgonzola, parmesan, taleggio",
    img: solo,
    cat: "Pizza (Klasik Hamur - 30 CM)",
    brand: 3,
  },
  {
    id: 44,
    name: "Antep Peynirli",
    price: "190 ₺",
    info: "Antep Peyniri, Roka, Sos",
    img: solo,
    cat: "Pizza (Klasik Hamur - 30 CM)",
    brand: 3,
  },
  {
    id: 45,
    name: "Gonzalo",
    price: "280 ₺",
    info: "S. Marzano, Domates Sos, Mozzarella, Fesleğen, Zeytinyağı",
    img: solo,
    cat: "Pizza (Napoli Hamuru - 30 CM)",
    brand: 3,
  },
  {
    id: 46,
    name: "Lorenzo",
    price: "320 ₺",
    info: "S. Marzano, Domates Sos, Mozzarella, Sucuk, K. Soğan",
    img: solo,
    cat: "Pizza (Napoli Hamuru - 30 CM)",
    brand: 3,
  },
  {
    id: 47,
    name: "L1",
    price: "180 ₺",
    info: "Kırmızı Et, Soğan, Beşamel Sos, Mozeralla",
    img: solo,
    cat: "Lazanya",
    brand: 3,
  },
  {
    id: 48,
    name: "L2",
    price: "180 ₺",
    info: "Kırmızı Et, Beşamel Sos, Acı Sos, Soğan, Mozeralla",
    img: solo,
    cat: "Lazanya",
    brand: 3,
  },
  {
    id: 49,
    name: "L3",
    price: "170 ₺",
    info: "Beşamel Sos, Mantar, Havuç, Kırmızı Biber, Mısır, Soğan, Mozeralla",
    img: solo,
    cat: "Lazanya",
    brand: 3,
  },
  {
    id: 50,
    name: "Chocolate Calzone",
    price: "120 ₺",
    img: solo,
    cat: "Tatlı",
    brand: 3,
  },
  {
    id: 51,
    name: "Antep Lahmacunu",
    price: "75 ₺",
    info: "Sarımsaklı Gaziantep Lahmacunu",
    img: sefa,
    cat: "Lahmacun",
    brand: 4,
  },
  {
    id: 52,
    name: "Soğanlı Lahmacun",
    price: "70 ₺",
    info: "Batı tarzı yuvarlak soğanlı lahmacun",
    img: sefa,
    cat: "Lahmacun",
    brand: 4,
  },
  {
    id: 53,
    name: "Kuşbaşılı",
    price: "230 ₺",
    info: "+ Kaşar: 10 ₺",
    img: sefa,
    cat: "Pide",
    brand: 4,
  },
  {
    id: 54,
    name: "Kıymalı",
    price: "230 ₺",
    info: "+ Kaşar: 10 ₺",
    img: sefa,
    cat: "Pide",
    brand: 4,
  },
  {
    id: 55,
    name: "Kaşarlı",
    price: "200 ₺",
    img: sefa,
    cat: "Pide",
    brand: 4,
  },
  {
    id: 56,
    name: "Karışık",
    price: "235 ₺",
    img: sefa,
    cat: "Pide",
    brand: 4,
  },
  {
    id: 57,
    name: "Sucuklu",
    price: "230 ₺",
    img: sefa,
    cat: "Pide",
    brand: 4,
  },
  {
    id: 58,
    name: "Sucuk - Kaşar",
    price: "240 ₺",
    img: sefa,
    cat: "Pide",
    brand: 4,
  },
  {
    id: 59,
    name: "Kavurmalı",
    price: "250 ₺",
    info: "+ Kaşar: 10 ₺",
    img: sefa,
    cat: "Pide",
    brand: 4,
  },
  {
    id: 60,
    name: "Ispanaklı",
    price: "180 ₺",
    img: sefa,
    cat: "Pide",
    brand: 4,
  },
  {
    id: 61,
    name: "Beyran",
    price: "175 ₺",
    info: "Kids: 155 ₺",
    img: mufa,
    cat: "Çorba",
    brand: 5,
  },
  {
    id: 62,
    name: "Et Paça",
    price: "185 ₺",
    info: "Kids: 165 ₺",
    img: mufa,
    cat: "Çorba",
    brand: 5,
  },
  {
    id: 63,
    name: "Mercimek Çorbası",
    price: "60 ₺",
    info: "Kids: 55 ₺",
    img: mufa,
    cat: "Çorba",
    brand: 5,
  },
  {
    id: 64,
    name: "Domates Çorbası",
    price: "75 ₺",
    info: "Kids: 65 ₺",
    img: mufa,
    cat: "Çorba",
    brand: 5,
  },
  {
    id: 65,
    name: "Ezogelin Çorbası",
    price: "65 ₺",
    info: "Kids: 60 ₺",
    img: mufa,
    cat: "Çorba",
    brand: 5,
  },
  {
    id: 66,
    name: "Sebze Çorbası",
    price: "75 ₺",
    info: "Kids: 65 ₺",
    img: mufa,
    cat: "Çorba",
    brand: 5,
  },
  {
    id: 67,
    name: "Kremalı Mantar",
    price: "90 ₺",
    info: "Kids: 80 ₺",
    img: mufa,
    cat: "Çorba",
    brand: 5,
  },
  {
    id: 68,
    name: "Tavuk Çorbası",
    price: "90 ₺",
    info: "Kids: 80 ₺",
    img: mufa,
    cat: "Çorba",
    brand: 5,
  },
  {
    id: 69,
    name: "Yayla Çorbası",
    price: "75 ₺",
    info: "Kids: 65 ₺",
    img: mufa,
    cat: "Çorba",
    brand: 5,
  },
  {
    id: 70,
    name: "Saray Çorbası",
    price: "125 ₺",
    info: "Kids: 115 ₺",
    img: mufa,
    cat: "Çorba",
    brand: 5,
  },
  {
    id: 71,
    name: "Sezar Salata",
    price: "140 ₺",
    info: "İceberg marul, ızgara tavuk, parmesan peyniri, salatalık, kruton ekmek",
    img: mufa,
    cat: "Salata",
    brand: 5,
  },
  {
    id: 72,
    name: "Ton Balıklı Salata",
    price: "145 ₺",
    info: "Mevsim yeşillikleri, ton balığı, roka, domates, salatalık, yeşil zeytin, kapari biber",
    img: mufa,
    cat: "Salata",
    brand: 5,
  },
  {
    id: 73,
    name: "Super Green",
    price: "125 ₺",
    info: "Akdeniz yeşillikleri, domates, salatalık, baby corn, nar, kurutukmuş domates",
    img: mufa,
    cat: "Salata",
    brand: 5,
  },
  {
    id: 74,
    name: "Tulumlu",
    price: "130 ₺",
    info: "Roka, tulum peyniri, iceberg marul, nar, zeytin, domates, salatalık",
    img: mufa,
    cat: "Salata",
    brand: 5,
  },
  {
    id: 75,
    name: "Barssica",
    price: "120 ₺",
    info: "Kızarmış karnabahar, Akdeniz yeşillikleri, mor lahana, havuç, avokado, nohut",
    img: mufa,
    cat: "Salata",
    brand: 5,
  },
  {
    id: 76,
    name: "Çoban Salata",
    price: "65 ₺",
    info: "Domates, salatalık, biber, soğan",
    img: mufa,
    cat: "Salata",
    brand: 5,
  },
  {
    id: 77,
    name: "Gavurdağı Salatası",
    price: "100 ₺",
    info: "Domates, salatalık, biber, soğan, ceviz",
    img: mufa,
    cat: "Salata",
    brand: 5,
  },
  {
    id: 78,
    name: "Haşlama İçli Köfte",
    price: "180 ₺",
    info: "Elazığ Usulü, dış harcı etli porsiyonda 6 adet mevcuttur",
    img: reyhan,
    cat: "Anadolu Lezzetleri",
    brand: 6,
  },
  {
    id: 79,
    name: "Dolma & Sarma",
    price: "90 ₺",
    info: "Porsiyon olarak servis edilir",
    img: reyhan,
    cat: "Anadolu Lezzetleri",
    brand: 6,
  },
  {
    id: 80,
    name: "Çökertme Kebabı",
    price: "250 ₺",
    info: "Porsiyon olarak servis edilir",
    img: reyhan,
    cat: "Anadolu Lezzetleri",
    brand: 6,
  },
  {
    id: 81,
    name: "Antep İçli Köfte",
    price: "50 ₺",
    info: "Kızartma içli köfte",
    img: reyhan,
    cat: "Anadolu Lezzetleri",
    brand: 6,
  },
  {
    id: 82,
    name: "Mantı",
    price: "150 ₺",
    info: "Yoğurt, üzeri tereyapı soslu",
    img: reyhan,
    cat: "Anadolu Lezzetleri",
    brand: 6,
  },
  {
    id: 83,
    name: "Soslu Misket Köfte",
    price: "185 ₺",
    info: "Soslu köfte topları",
    img: reyhan,
    cat: "Anadolu Lezzetleri",
    brand: 6,
  },
  {
    id: 84,
    name: "Classic Burger",
    price: "155 ₺",
    info: "Burger Eti, Karamelize Soğan, Soslu Iceberg, Domates, Salatalık Turşusu, Burger Sosu",
    img: burger,
    cat: "Burger",
    brand: 8,
  },
  {
    id: 85,
    name: "Cheese Burger",
    price: "165 ₺",
    info: "Burger Eti, Cheddar Peyniri, Karamelize Soğan, Soslu Iceberg, Salatalık Turşusu, Burger Sosu",
    img: burger,
    cat: "Burger",
    brand: 8,
  },
  {
    id: 86,
    name: "Walter Burger",
    price: "175 ₺",
    info: "Burger Eti, Cheddar Peyniri, Kibrit Patates, Karamelize Soğan, Soslu Iceberg, Salatalık Turşusu, Burger Sosu",
    img: burger,
    cat: "Burger",
    brand: 8,
  },
  {
    id: 87,
    name: "Trüf Burger",
    price: "190 ₺",
    info: "Burger Eti, Cheddar Peyniri, Trüf Sosu, Karamelize Soğan, Soslu Iceberg, Salatalık Turşusu, Burger Sosu",
    img: burger,
    cat: "Burger",
    brand: 8,
  },
  {
    id: 88,
    name: "Füme Burger",
    price: "225 ₺",
    info: "Burger Eti, Cheddar Peyniri, Füme Kaburga, Karamelize Soğan, Soslu Iceberg, Salatalık Turşusu, Burger Sosu",
    img: burger,
    cat: "Burger",
    brand: 8,
  },
  {
    id: 89,
    name: "Hot Burger",
    price: "190 ₺",
    info: "Burger Eti, Cheddar Peyniri, Acı Sos, Karamelize Soğan, Soslu Iceberg, Salatalık Turşusu, Burger Sosu",
    img: burger,
    cat: "Burger",
    brand: 8,
  },
  {
    id: 90,
    name: "BBQ Burger",
    price: "195 ₺",
    info: "Mangalda Burger Eti, Cheddar Peyniri, Kibrit Patates, Karamelize Soğan, Soslu Iceberg, Salatalık Turşusu, Burger Sosu",
    img: burger,
    cat: "Burger",
    brand: 8,
  },
  {
    id: 91,
    name: "Double Burger",
    price: "240 ₺",
    info: "Double Burger Eti, Doblue Cheddar Peyniri, Kibrit Patates, Karamelize Soğan, Burger Sosu",
    img: burger,
    cat: "Burger",
    brand: 8,
  },
  {
    id: 92,
    name: "Tavuk Döner",
    price: "65 ₺",
    img: lobik,
    cat: "Döner",
    brand: 7,
  },
  {
    id: 93,
    name: "Nohut Dürüm",
    price: "95 ₺",
    img: lobik,
    cat: "Döner",
    brand: 7,
  },
  {
    id: 94,
    name: "Kızartma Dürüm",
    price: "55 ₺",
    img: lobik,
    cat: "Döner",
    brand: 7,
  },
  {
    id: 95,
    name: "Tavuk Şavurma",
    price: "55 ₺",
    img: lobik,
    cat: "Döner",
    brand: 7,
  },
  {
    id: 96,
    name: "Tavuk Fajita",
    price: "80 ₺",
    img: lobik,
    cat: "Döner",
    brand: 7,
  },
  {
    id: 97,
    name: "Çıtır Tavuk Dürüm",
    price: "110 ₺",
    img: lobik,
    cat: "Döner",
    brand: 7,
  },
  {
    id: 98,
    name: "Ciğer Kavurma",
    price: "50 ₺",
    img: lobik,
    cat: "Döner",
    brand: 7,
  },
  {
    id: 99,
    name: "Ökçe Dürüm",
    price: "55 ₺",
    img: lobik,
    cat: "Döner",
    brand: 7,
  },
  {
    id: 100,
    name: "Classic Fred",
    price: "150 ₺",
    info: "Kızarmış tavul, soslu iceberg, kırmızı soğan",
    img: fried,
    cat: "Burger",
    brand: 9,
  },
  {
    id: 101,
    name: "Cheddar Fred",
    price: "160 ₺",
    info: "Kızarmış tavuk, cheddar, soslu iceberg, kırmızı soğan",
    img: fried,
    cat: "Burger",
    brand: 9,
  },
  {
    id: 102,
    name: "Trüf Mondy",
    price: "180 ₺",
    info: "Kızarmış tavuk, trüf sos, soslu iceberg, kırmızı soğan",
    img: fried,
    cat: "Burger",
    brand: 9,
  },
  {
    id: 103,
    name: "Hot Fred",
    price: "175 ₺",
    info: "Kızarmış tavuk, acı sos, soslu iceberg, kırmızı soğan",
    img: fried,
    cat: "Burger",
    brand: 9,
  },
  {
    id: 104,
    name: "Honey Fred",
    price: "180 ₺",
    info: "Kızarmış tavuk, ballı sos, kırmızı lahana,",
    img: fried,
    cat: "Burger",
    brand: 9,
  },
  {
    id: 105,
    name: "Chicken Ball",
    price: "80 ₺",
    info: "6 adet Kızarmış tavuk topları",
    img: fried,
    cat: "Çıtırlar",
    brand: 9,
  },
  {
    id: 106,
    name: "Chicken Popcorn",
    price: "80 ₺",
    info: "6 adet Kızarmış tavuk parçaları",
    img: fried,
    cat: "Çıtırlar",
    brand: 9,
  },
  {
    id: 107,
    name: "Fred Box",
    price: "230 ₺",
    info: "1 Tavuk göğüs, 4 popcorn 4 tavuk topları, 2 kanat",
    img: fried,
    cat: "Çıtırlar",
    brand: 9,
  },
  {
    id: 108,
    name: "Soslu Kanat",
    price: "225 ₺",
    info: "6 adet teriyaki soslu kanat",
    img: fried,
    cat: "Specials",
    brand: 9,
  },
  {
    id: 109,
    name: "Çıtır Tavuk Dürüm",
    price: "110 ₺",
    img: fried,
    cat: "Specials",
    brand: 9,
  },
  {
    id: 110,
    name: "Fettuccine",
    price: "170 ₺",
    img: pion,
    cat: "Makarna",
    brand: 10,
  },
  {
    id: 111,
    name: "Penne",
    price: "160 ₺",
    img: pion,
    cat: "Makarna",
    brand: 10,
  },
  {
    id: 112,
    name: "Anne Makarnası",
    price: "160 ₺",
    img: pion,
    cat: "Makarna",
    brand: 10,
  },
  {
    id: 113,
    name: "Ravioli",
    price: "180 ₺",
    img: pion,
    cat: "Makarna",
    brand: 10,
  },
  {
    id: 114,
    name: "Noodle",
    price: "140 ₺",
    img: pion,
    cat: "Makarna",
    brand: 10,
  },
  {
    id: 115,
    name: "Renkli Makarna",
    price: "80 ₺",
    img: pion,
    cat: "Makarna",
    brand: 10,
  },
  {
    id: 116,
    name: "Mac & Cheese",
    price: "140 ₺",
    img: pion,
    cat: "Makarna",
    brand: 10,
  },
  {
    id: 117,
    name: "Sade Kıyma",
    price: "280 ₺",
    info: "240 gr kuzu erkek eti\nDürüm:140 ₺",
    img: hesiar,
    cat: "Kebap & Köfte",
    brand: 11,
  },
  {
    id: 118,
    name: "Adana",
    price: "280 ₺",
    info: "240 gr kuzu erkek eti, pul biber, kapya biber\nDürüm: 140 ₺",
    img: hesiar,
    cat: "Kebap & Köfte",
    brand: 11,
  },
  {
    id: 119,
    name: "Kuşbaşı",
    price: "300 ₺",
    info: "210 gr kuzu erkek eti\nDürüm: 150 ₺",
    img: hesiar,
    cat: "Kebap & Köfte",
    brand: 11,
  },
  {
    id: 120,
    name: "Karışık Kebap",
    price: "200 ₺",
    info: "Kıyma, Kuşbaşı, Ciğer & Tavuk",
    img: hesiar,
    cat: "Kebap & Köfte",
    brand: 11,
  },
  {
    id: 121,
    name: "Ali Nazik",
    price: "310 ₺",
    info: "Kuşbaşı ya da kıyma tercihi ile",
    img: hesiar,
    cat: "Kebap & Köfte",
    brand: 11,
  },
  {
    id: 122,
    name: "Pideli Köfte",
    price: "280 ₺",
    info: "iskender usulü, 240 gr dana eti, yoğurt, tereyağı",
    img: hesiar,
    cat: "Kebap & Köfte",
    brand: 11,
  },
  {
    id: 123,
    name: "Sebzeli Kıyma",
    price: "280 ₺",
    info: "240 gr kuzu erkek eti\nDürüm: 140 ₺",
    img: hesiar,
    cat: "Kebap & Köfte",
    brand: 11,
  },
  {
    id: 124,
    name: "Tavuk Şiş",
    price: "250 ₺",
    info: "300 gr tavuk sarma\nDürüm: 125 ₺",
    img: hesiar,
    cat: "Kebap & Köfte",
    brand: 11,
  },
  {
    id: 125,
    name: "Acı - Tatlı Tavuk",
    price: "250 ₺",
    info: "300 gr tavuk sarma ve özel sos",
    img: hesiar,
    cat: "Kebap & Köfte",
    brand: 11,
  },
  {
    id: 126,
    name: "Urfa Usulü Ciğer",
    price: "290 ₺",
    info: "220 gr kuzu erkek eti\nDürüm: 145 ₺",
    img: hesiar,
    cat: "Kebap & Köfte",
    brand: 11,
  },
  {
    id: 127,
    name: "Kuzu Lokum",
    price: "350 ₺",
    info: "250 gr kuzu erkek eti",
    img: hesiar,
    cat: "Kebap & Köfte",
    brand: 11,
  },
  {
    id: 128,
    name: "Köfte",
    price: "260 ₺",
    info: "240 gr dana eti",
    img: hesiar,
    cat: "Kebap & Köfte",
    brand: 11,
  },
  {
    id: 129,
    name: "Türk Kahvesi",
    price: "40 ₺",
    img: soon,
    cat: "Kahve Çeşitleri",
    brand: 12,
  },
  {
    id: 130,
    name: "Latte",
    price: `65 ₺ \u00A075 ₺`,
    img: soon,
    cat: "Kahve Çeşitleri",
    brand: 12,
  },
  {
    id: 131,
    name: "Menengiç",
    price: "40 ₺",
    img: soon,
    cat: "Kahve Çeşitleri",
    brand: 12,
  },
  {
    id: 132,
    name: "Cappuchino",
    price: "65 ₺ / 75 ₺",
    img: soon,
    cat: "Kahve Çeşitleri",
    brand: 12,
  },
  {
    id: 133,
    name: "Espresso",
    price: "58 ₺",
    img: soon,
    cat: "Kahve Çeşitleri",
    brand: 12,
  },
  {
    id: 134,
    name: "Americano",
    price: "65 ₺ / 75 ₺",
    img: soon,
    cat: "Kahve Çeşitleri",
    brand: 12,
  },
  {
    id: 135,
    name: "Cortado",
    price: "62 ₺",
    img: soon,
    cat: "Kahve Çeşitleri",
    brand: 12,
  },
  {
    id: 136,
    name: "Mocha",
    price: "70 ₺ / 80 ₺",
    img: soon,
    cat: "Kahve Çeşitleri",
    brand: 12,
  },
  {
    id: 137,
    name: "Flat White",
    price: "62 ₺",
    img: soon,
    cat: "Kahve Çeşitleri",
    brand: 12,
  },
  {
    id: 138,
    name: "Filtre Kahve",
    price: "60 ₺ / 70 ₺",
    img: soon,
    cat: "Kahve Çeşitleri",
    brand: 12,
  },
  {
    id: 139,
    name: "Kış Çayı",
    price: "40 ₺",
    img: soon,
    cat: "Bitki Çayları",
    brand: 12,
  },
  {
    id: 140,
    name: "Ihlamur",
    price: "40 ₺",
    img: soon,
    cat: "Bitki Çayları",
    brand: 12,
  },
  {
    id: 141,
    name: "Nane - Limon",
    price: "40 ₺",
    img: soon,
    cat: "Bitki Çayları",
    brand: 12,
  },
  {
    id: 142,
    name: "Hibiscus",
    price: "40 ₺",
    img: soon,
    cat: "Bitki Çayları",
    brand: 12,
  },
  {
    id: 143,
    name: "Su",
    price: "10 ₺",
    img: soon,
    cat: "Ambalajlı İçecekler",
    brand: 12,
  },
  {
    id: 144,
    name: "Meyve Suyu",
    price: "35 ₺",
    img: soon,
    cat: "Ambalajlı İçecekler",
    brand: 12,
  },
  {
    id: 145,
    name: "Ayran",
    price: "20 ₺",
    img: soon,
    cat: "Ambalajlı İçecekler",
    brand: 12,
  },
  {
    id: 146,
    name: "Gazoz",
    price: "35 ₺",
    img: soon,
    cat: "Ambalajlı İçecekler",
    brand: 12,
  },
  {
    id: 147,
    name: "Kola",
    price: "35 ₺",
    img: soon,
    cat: "Ambalajlı İçecekler",
    brand: 12,
  },
  {
    id: 148,
    name: "Soda",
    price: "20 ₺",
    img: soon,
    cat: "Ambalajlı İçecekler",
    brand: 12,
  },
  {
    id: 149,
    name: "Soğuk Çay",
    price: "35 ₺",
    img: soon,
    cat: "Ambalajlı İçecekler",
    brand: 12,
  },
  {
    id: 150,
    name: "Berry Hibiscus",
    price: "90 ₺",
    img: soon,
    cat: "Ev Yapımı İçecekler",
    brand: 12,
  },
  {
    id: 151,
    name: "Passion",
    price: "90 ₺",
    img: soon,
    cat: "Ev Yapımı İçecekler",
    brand: 12,
  },
  {
    id: 152,
    name: "Cool Lime",
    price: "90 ₺",
    img: soon,
    cat: "Ev Yapımı İçecekler",
    brand: 12,
  },
  {
    id: 153,
    name: "Orman Meyvesi",
    price: "90 ₺",
    img: soon,
    cat: "Ev Yapımı İçecekler",
    brand: 12,
  },
  {
    id: 154,
    name: "Limonata",
    price: "90 ₺",
    img: soon,
    cat: "Ev Yapımı İçecekler",
    brand: 12,
  },
  {
    id: 155,
    name: "Çikolatalı Magnolia",
    price: "100 ₺",
    img: soon,
    cat: "Pasta Çeşitleri",
    brand: 12,
  },
  {
    id: 156,
    name: "Köstebek",
    price: "90 ₺",
    img: soon,
    cat: "Pasta Çeşitleri",
    brand: 12,
  },
  {
    id: 157,
    name: "Çilek Magnolia",
    price: "100 ₺",
    img: soon,
    cat: "Pasta Çeşitleri",
    brand: 12,
  },
  {
    id: 158,
    name: "Mozaik",
    price: "90 ₺",
    img: soon,
    cat: "Pasta Çeşitleri",
    brand: 12,
  },
  {
    id: 159,
    name: "Sadrazam",
    price: "90 ₺",
    img: soon,
    cat: "Pasta Çeşitleri",
    brand: 12,
  },
  {
    id: 160,
    name: "Cookie",
    price: "100 ₺",
    img: soon,
    cat: "Pasta Çeşitleri",
    brand: 12,
  },
];
export const allLabel = [
  { id: 0, name: "all", icon: "" },
  { id: 1, name: "Kahvaltı", icon: "" },
  { id: 2, name: "Soğuk Mezeler", icon: "fa-regular fa-snowflake" },
  { id: 3, name: "Sıcak Mezeler", icon: "fa-solid fa-fire" },
  { id: 5, name: "Pizza", icon: "fa-solid fa-pizza-slice" },
  { id: 6, name: "Lazanya", icon: "fa-solid fa-martini-glass-citrus" },
  { id: 7, name: "Çorba", icon: "fa-solid fa-martini-glass-citrus" },
  { id: 8, name: "Salata", icon: "fa-solid fa-martini-glass-citrus" },
  { id: 9, name: "lol" },
  { id: 10, name: "Köfte", icon: "fa-solid fa-martini-glass-citrus" },
  { id: 11, name: "Doner", icon: "fa-solid fa-hotdog" },
  { id: 12, name: "Burger", icon: "fa-solid fa-burger" },
  { id: 13, name: "Kizarmis", icon: "fa-solid fa-solar-panel" },
  { id: 14, name: "Makarna", icon: "fa-solid fa-solar-panel" },
  { id: 15, name: "Kebap", icon: "fa-solid fa-solar-panel" },
  { id: 16, name: "Sicak", icon: "fa-solid fa-solar-panel" },
  { id: 17, name: "Soguk", icon: "fa-solid fa-solar-panel" },
];
export const logos = [
  { id: 1, img: `${img}`, name: "leyla" },
  { id: 2, img: `${img2}`, name: "mucmer" },
  { id: 3, img: `${img3}`, name: "solo" },
  { id: 4, img: `${img4}`, name: "SEFA" },
  { id: 5, img: `${img5}`, name: "Mufa" },
  { id: 6, img: `${img6}`, name: "Reyhan" },
  { id: 7, img: `${img7}`, name: "lobik" },
  { id: 8, img: `${img8}`, name: "1312 burgar" },
  { id: 9, img: `${img9}`, name: "fred moudy" },
  { id: 10, img: `${img10}`, name: "Pion" },
  { id: 11, img: `${img12}`, name: "hisaralti" },
  { id: 12, img: `${img13}`, name: "Soon" },
];
